### ISSUE TITLE
"Chips" selection bug 

### ISSUE THREAD

**Issue by emil-perhinschi** [PearlVentures/Essence#9]
Component List -> Chips: open the "chip" and while keeping the mouse over the strings in each element try to select the row: fail most of the times, with some flickering of the background while you move the mouse up and down the list; no problem selecting each element while clicking to the right of the strings

browser: Firefox 37.0.2 on Linux Mint 17.1 Rebecca

**Comment by hetmann** [comment]
Hi @emil-perhinschi,

We fixed the bug, check it on the website at Components -> Chips

Thank you for the feedback.

**Comment by raulmatei** [comment]
This is still reproducible, have a look on the following screenshot:
![chips](https://cloud.githubusercontent.com/assets/1718341/7775949/f4f60bb2-00bf-11e5-88bf-151bb0197897.gif)

**Comment by hetmann** [comment]
Resolved: added background-color for class .e-chip .open on li hover (file: chips.less)
